name: commit

on: [push]

jobs:
  commit:
    name: commit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: alexpapworth/github-action-target
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
