name: commit

on: [push]

jobs:
  commit:
    name: commit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: alexpapworth/github-action-target
